/* ==========================================================================
   variable-catalog.mjs
   One entry per recorded occurrence of a congestion variable in Makati.

   Categories and variable names mirror Traffic_Variables_Data_Sheet.xlsx
   (50 variables / 7 categories). A variable may legitimately appear several
   times — once per corridor and time window where it was observed.

   Fields
     cat    category (must exist in CAT_CODE)
     v      variable name (sheet wording, Filipino terms preserved)
     eff    'increases' | 'decreases'  — direction of effect on congestion
     place  ['bo', bottleneckId] | ['path', corridor, fraction, pathIdx?] | ['pt', lat, lng]
     loc    human-readable location the row was recorded at
     hours  [hourStart, hourEnd] inclusive, 0–23 (end < start wraps midnight)
     ci     congestion index (0–100) paired with the observation; the
            congestion_level column is derived from it so the two can never disagree
     value  observed value · unit · threshold = planning trigger, not a legal limit
     w      contribution weight (relative, renormalised to 100% at load time)
     conf   confidence in the observation (0–1)
     src    provenance string shown in the UI and in exports
   ========================================================================== */

export const CAT_CODE = {
  'Vehicle Related Variables': 'VEH',
  'Urban Development Variables': 'URB',
  'Driver Based Variables': 'DRV',
  'Pedestrian Variables': 'PED',
  'Safety Hazards Variables': 'SAF',
  'Event Variables': 'EVT',
  'Weather Variables': 'WX'
};

const VEH = 'Vehicle Related Variables';
const URB = 'Urban Development Variables';
const DRV = 'Driver Based Variables';
const PED = 'Pedestrian Variables';
const SAF = 'Safety Hazards Variables';
const EVT = 'Event Variables';
const WX = 'Weather Variables';

export const CATALOG = [
  /* ---------------- Vehicle Related — how vehicles are operated ---------- */
  { cat: VEH, v: 'Public utility vehicles', eff: 'increases', place: ['bo', 'edsa-ayala'],
    loc: 'EDSA–Ayala terminal kerbside (MRT-3 bus bay)', hours: [18, 20], ci: 88,
    value: 96, unit: 'PUV arrivals/h', threshold: 60, w: .34, conf: .82,
    src: 'PUV GPS dwell feed + MRT-3 tap counts',
    note: 'Bus and jeepney units stage on the running lane while waiting for headway slots; 94 s mean bay dwell.' },
  { cat: VEH, v: 'Public utility vehicles', eff: 'increases', place: ['bo', 'buendia-makati'],
    loc: 'Buendia × Makati Ave westbound kerb', hours: [17, 19], ci: 75,
    value: 54, unit: 'PUV arrivals/h', threshold: 40, w: .28, conf: .74,
    src: 'Jeepney GPS dwell feed (15 routes)',
    note: 'Jeepney queue spillback from the loading bay reduces the kerb lane to a stop-and-go channel.' },
  { cat: VEH, v: 'Public utility vehicles', eff: 'increases', place: ['bo', 'ayala-paseo'],
    loc: 'Ayala Ave × Paseo de Roxas frontage', hours: [7, 9], ci: 79,
    value: 62, unit: 'PUV arrivals/h', threshold: 45, w: .31, conf: .78,
    src: 'PUV GPS dwell + LGU enforcer logs',
    note: 'AM office drop-off demand competes with bus and jeepney loading in the same 60 m of kerb.' },
  { cat: VEH, v: 'Vehicle size', eff: 'increases', place: ['path', 'buendia', .30],
    loc: 'Buendia eastbound — Chino Roces industrial strip', hours: [8, 10], ci: 54,
    value: 18, unit: '% heavy vehicles', threshold: 10, w: .22, conf: .70,
    src: 'Cordon survey 2026-08 · cargo counts',
    note: 'Trucks serving Pasong Tamo need two lanes to turn, stalling the merged lane behind them.' },
  { cat: VEH, v: 'Vehicle size', eff: 'increases', place: ['bo', 'poblacion-jpr'],
    loc: 'J.P. Rizal Ave (Poblacion west)', hours: [20, 22], ci: 71,
    value: 12, unit: '% heavy vehicles', threshold: 8, w: .24, conf: .66,
    src: 'Field survey 2026-09',
    note: 'Delivery trucks double-park on a carriageway that is only 6.5 m wide at the frontage.' },
  { cat: VEH, v: 'Arrival & Departure', eff: 'increases', place: ['bo', 'ayala-paseo'],
    loc: 'Ayala Ave × Paseo de Roxas drop-off kerb', hours: [7, 9], ci: 82,
    value: 310, unit: 'drop-offs/h', threshold: 180, w: .30, conf: .80,
    src: 'Anonymised probe stop events (2,140 stops/wk in-lane)',
    note: 'Tower arrivals concentrate inside a 25-minute window, so the kerb saturates long before the peak ends.' },
  { cat: VEH, v: 'Arrival & Departure', eff: 'increases', place: ['bo', 'sl-legazpi'],
    loc: 'Legazpi Village school and office drop-off zone', hours: [7, 8], ci: 58,
    value: 160, unit: 'drop-offs/h', threshold: 90, w: .22, conf: .72,
    src: 'School shuttle logs · enforcer tally',
    note: 'Six institutions release inside the same 25 minutes on streets with no kiss-and-ride bay.' },
  { cat: VEH, v: 'Number of turning vehicles', eff: 'increases', place: ['bo', 'edsa-buendia'],
    loc: 'EDSA × Buendia flyover ramps and U-turn slot', hours: [8, 10], ci: 86,
    value: 1420, unit: 'turning veh/h', threshold: 900, w: .33, conf: .81,
    src: 'MMDA junction count 2026-08',
    note: 'Four weaving manoeuvres must complete inside 600 m, so the turn bay blocks the through lanes.' },
  { cat: VEH, v: 'Number of turning vehicles', eff: 'increases', place: ['bo', 'ayala-paseo'],
    loc: 'Ayala Ave × Paseo de Roxas (all approaches)', hours: [17, 19], ci: 63,
    value: 780, unit: 'turning veh/h', threshold: 600, w: .21, conf: .73,
    src: 'MMDA junction count 2026-08',
    note: 'PM turning demand exceeds the pocket length, leaving right-turners queued in the through lane.' },
  { cat: VEH, v: 'Intersection changes', eff: 'increases', place: ['bo', 'edsa-ayala'],
    loc: 'EDSA–Ayala U-turn slot and busway merge', hours: [17, 19], ci: 84,
    value: 6, unit: 'lane changes/veh', threshold: 3, w: .26, conf: .68,
    src: 'Video analytics (4 cameras)',
    note: 'Every vehicle crossing the belt changes lanes at least six times, so turbulence never dissipates.' },

  /* ---------------- Urban Development — built environment and demand ------ */
  { cat: URB, v: 'Number of vehicles', eff: 'increases', place: ['path', 'edsa', .45],
    loc: 'EDSA northbound — CBD approach', hours: [17, 20], ci: 89,
    value: 11400, unit: 'veh/h', threshold: 8000, w: .38, conf: .86,
    src: 'Probe vehicle counts (48 h sample)',
    note: 'Peak demand is 1.4× the design volume; the queue is demand-driven, not incident-driven.' },
  { cat: URB, v: 'Number of vehicles', eff: 'increases', place: ['path', 'ayala', .55],
    loc: 'Ayala Ave spine (EDSA–Makati Ave)', hours: [17, 19], ci: 80,
    value: 2400, unit: 'veh/h', threshold: 1800, w: .29, conf: .79,
    src: 'Probe vehicle counts + mall access counts',
    note: 'Through traffic and mall-bound traffic share the same two lanes all evening.' },
  { cat: URB, v: 'Road capacity', eff: 'increases', place: ['path', 'edsa', .60],
    loc: 'EDSA mixed-flow lanes (3 of 5 reserved for busway/turns)', hours: [7, 20], ci: 85,
    value: 1.18, unit: 'v/c ratio', threshold: .85, w: .35, conf: .90,
    src: 'HCM capacity audit 2026 · LGU link inventory',
    note: 'Structural capacity deficit: it persists across the whole day, not only in peaks.' },
  { cat: URB, v: 'Road capacity', eff: 'increases', place: ['path', 'ayala', .40],
    loc: 'Ayala Ave — two lanes per direction, no turning pockets', hours: [7, 20], ci: 76,
    value: 1.06, unit: 'v/c ratio', threshold: .85, w: .27, conf: .87,
    src: 'LGU link inventory · saturation flow survey',
    note: 'Any single curbside obstruction pushes the link above capacity because there is no spare lane.' },
  { cat: URB, v: 'Frequency of traffic accidents', eff: 'increases', place: ['bo', 'edsa-buendia'],
    loc: 'EDSA–Buendia interchange', hours: [17, 19], ci: 78,
    value: 11, unit: 'crashes/30 days', threshold: 4, w: .25, conf: .75,
    src: 'MMDA incident feed + PNP blotter',
    note: 'Each crash removes one of three lanes for 22 minutes on average.' },
  { cat: URB, v: 'Frequency of traffic accidents', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network (all monitored links)', hours: [17, 20], ci: 57,
    value: 34, unit: 'crashes/30 days', threshold: 18, w: .18, conf: .70,
    src: 'MMDA incident feed + PNP blotter',
    note: 'Network-wide baseline used to normalise the corridor incident KPI.' },
  { cat: URB, v: 'Time of day', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [0, 23], ci: 55,
    value: 2, unit: 'peak waves/day', threshold: 2, w: .20, conf: .90,
    src: '24-hour probe profile (this prototype’s hourly curve)',
    note: 'Context variable: supplies the hour-of-day shape that every other row is read against.' },
  { cat: URB, v: 'Road closures', eff: 'increases', place: ['bo', 'buendia-chinoroces'],
    loc: 'Buendia × Chino Roces — utility works diversion', hours: [21, 5], ci: 60,
    value: 1, unit: 'closed lanes', threshold: 0, w: .20, conf: .65,
    src: 'LGU works permit register (DPWH/Maynilad notices)',
    note: 'Night window: works authorised 21:00–05:00, so the closure never clears the AM peak.' },
  { cat: URB, v: 'Road construction', eff: 'increases', place: ['path', 'ayala', .70],
    loc: 'Ayala Ave reblocking — Makati Ave end', hours: [23, 4], ci: 38,
    value: 400, unit: 'm of carriageway', threshold: 0, w: .15, conf: .72,
    src: 'LGU works permit register 2026-09',
    note: 'Pavement works scheduled overnight; residual lane narrowing is reported until 06:00.' },
  { cat: URB, v: 'Number of merging lanes', eff: 'increases', place: ['bo', 'edsa-buendia'],
    loc: 'Buendia flyover merge taper (short taper, 60 m)', hours: [7, 9], ci: 87,
    value: 3, unit: 'merge points/600 m', threshold: 1, w: .32, conf: .83,
    src: 'Road geometry audit + video analytics',
    note: 'Merging three streams inside 60 m caps busway throughput regardless of signal timing.' },
  { cat: URB, v: 'Availability of alternative routes', eff: 'decreases', place: ['path', 'poblacion', .50, 0],
    loc: 'Poblacion one-way grid — five parallel streets', hours: [10, 16], ci: 28,
    value: 5, unit: 'parallel routes', threshold: 2, w: .16, conf: .70,
    src: 'Network topology audit',
    note: 'Decreasing variable: grid redundancy absorbs inter-peak traffic, which is why Poblacion reads low at midday.' },
  { cat: URB, v: 'Presence of bottlenecks', eff: 'increases', place: ['bo', 'ayala-makati'],
    loc: 'Ayala Ave × Makati Ave signalised junction', hours: [17, 19], ci: 81,
    value: 3, unit: 'critical bottlenecks on link', threshold: 0, w: .30, conf: .84,
    src: 'Floating-car queue-length analysis',
    note: 'Queue reaches Paseo de Roxas in the PM peak; LOS F for 96 minutes.' },

  /* ---------------- Driver Based — behaviour at the kerb and junction ---- */
  { cat: DRV, v: 'Illegal Parking / Bad Parking', eff: 'increases', place: ['bo', 'poblacion-jpr'],
    loc: 'J.P. Rizal Ave and A. Bonifacio frontage', hours: [20, 2], ci: 86,
    value: 1, unit: 'lanes lost', threshold: 0, w: .34, conf: .79,
    src: 'Night enforcement logs + CCTV review (11:00 pm–01:00 am)',
    note: 'Wrapping window: night-economy double parking takes one lane from 20:00 until after midnight.' },
  { cat: DRV, v: 'Illegal Parking / Bad Parking', eff: 'increases', place: ['bo', 'ayala-makati'],
    loc: 'Ayala Ave curbside (Makati Ave end)', hours: [17, 19], ci: 74,
    value: 68, unit: 'parked-in-lane events/h', threshold: 12, w: .26, conf: .72,
    src: 'Enforcement camera review (18 cameras)',
    note: 'Short-stay parking in the outer lane is the single most repeated violation on the corridor.' },
  { cat: DRV, v: 'Illegal Parking / Bad Parking', eff: 'increases', place: ['bo', 'sl-legazpi'],
    loc: 'Legazpi Village commercial strip', hours: [12, 14], ci: 52,
    value: 42, unit: 'parked-in-lane events/h', threshold: 10, w: .20, conf: .68,
    src: 'Midday enforcer patrol tally',
    note: 'Lunchtime parking pressure, well below the CBD peaks but visible in the heat layer.' },
  { cat: DRV, v: 'Unconventional stops', eff: 'increases', place: ['bo', 'ayala-paseo'],
    loc: 'Ayala Ave outer lane (Paseo de Roxas to Makati Ave)', hours: [7, 9], ci: 79,
    value: 340, unit: 'violations/week', threshold: 50, w: .31, conf: .86,
    src: 'Enforcement camera review + in-lane dwell events',
    note: 'Informal loading occupies the outer lane; 11 minutes of the corridor’s AM delay is attributed here.' },
  { cat: DRV, v: 'Mga siksik sa kalsada (tricycle, motorcycle, jeeps)', eff: 'increases', place: ['bo', 'poblacion-jpr'],
    loc: 'Poblacion streets — tricycle and e-trike routes', hours: [18, 21], ci: 77,
    value: 410, unit: 'units/h', threshold: 220, w: .28, conf: .70,
    src: 'Barangay traffic counts 2026-08',
    note: 'Counterflow tricycles and e-trikes create six head-on conflict points per kilometre.' },
  { cat: DRV, v: 'Mga siksik sa kalsada (tricycle, motorcycle, jeeps)', eff: 'increases', place: ['bo', 'edsa-buendia'],
    loc: 'EDSA service road (moped filtering)', hours: [17, 19], ci: 68,
    value: 380, unit: 'units/h', threshold: 150, w: .22, conf: .66,
    src: 'Service-road count station 2026-09',
    note: 'Filtering motorcycles occupy the gutter, so right-turners cannot complete their manoeuvre.' },
  { cat: DRV, v: 'Random Commuter Stops (public transport stops)', eff: 'increases', place: ['path', 'edsa', .50],
    loc: 'EDSA Carousel bay lane', hours: [7, 9], ci: 77,
    value: 190, unit: 'flag-downs/h', threshold: 60, w: .27, conf: .75,
    src: 'PUV GPS stop events (off-bay boardings)',
    note: 'Boardings outside the designated bay reset the bus dwell clock and block the bay lane.' },
  { cat: DRV, v: 'Random Commuter Stops (public transport stops)', eff: 'increases', place: ['bo', 'buendia-makati'],
    loc: 'Buendia westbound kerb', hours: [17, 19], ci: 74,
    value: 150, unit: 'flag-downs/h', threshold: 50, w: .25, conf: .72,
    src: 'PUV GPS stop events + kerb observation',
    note: 'Unmarked stopping points along 300 m of kerb defeat the formal loading bay provision.' },
  { cat: DRV, v: 'Unexpected turns', eff: 'increases', place: ['bo', 'edsa-ayala'],
    loc: 'EDSA–Ayala service road to main lanes', hours: [17, 19], ci: 66,
    value: 240, unit: 'unexpected turns/h', threshold: 120, w: .21, conf: .64,
    src: 'Video analytics (turn-path classification)',
    note: 'Late lane entries from the service road force braking waves into the main carriageway.' },
  { cat: DRV, v: 'Confusion between drivers', eff: 'increases', place: ['bo', 'edsa-buendia'],
    loc: 'Buendia interchange weaving zone', hours: [8, 9], ci: 80,
    value: 4, unit: 'conflict points/600 m', threshold: 1, w: .28, conf: .69,
    src: 'Video analytics (conflict-point detection)',
    note: 'Ramp, busway and U-turn traffic share one decision zone with no lane discipline markings.' },
  { cat: DRV, v: 'Road sign confusion', eff: 'increases', place: ['bo', 'poblacion-hub'],
    loc: 'Makati–Mandaluyong bridge approach', hours: [18, 20], ci: 59,
    value: 6, unit: 'conflicting sign types/100 m', threshold: 1, w: .18, conf: .60,
    src: 'Signage audit walkthrough 2026-09',
    note: 'Three regulatory systems share the approach; drivers brake to read them at the merge point.' },
  { cat: DRV, v: 'Driver behavior', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [17, 20], ci: 63,
    value: 46, unit: '% non-compliant acts', threshold: 15, w: .20, conf: .66,
    src: 'Field observation survey (12 junctions, 2 h each)',
    note: 'Network-wide behaviour baseline: blocking the box, lane straddling, and no-signal turns.' },
  { cat: DRV, v: 'Driver Discipline', eff: 'increases', place: ['path', 'ayala', .35],
    loc: 'Ayala Ave mid-block', hours: [12, 14], ci: 55,
    value: 38, unit: '% non-compliant acts', threshold: 15, w: .19, conf: .63,
    src: 'Midday observation survey 2026-09',
    note: 'Off-peak discipline is worse than peak: enforcement is concentrated in the peaks.' },
  { cat: DRV, v: 'Traffic rule violations', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network (LGU ticketing data)', hours: [17, 19], ci: 76,
    value: 940, unit: 'violations/week', threshold: 200, w: .29, conf: .78,
    src: 'LGU ticketing system export 2026-09',
    note: 'Ticket volume is a proxy for enforcement exposure, not for absolute violation counts.' },
  { cat: DRV, v: 'Traffic rule violations', eff: 'increases', place: ['bo', 'edsa-ayala'],
    loc: 'EDSA–Ayala busway', hours: [7, 9], ci: 72,
    value: 520, unit: 'violations/week', threshold: 150, w: .24, conf: .72,
    src: 'Busway CCTV enforcement (automatic capture)',
    note: 'Private vehicles entering the busway during the AM window collapse carousel headway.' },
  { cat: DRV, v: 'Overtaking', eff: 'increases', place: ['path', 'buendia', .55],
    loc: 'Buendia eastbound (two-lane segment)', hours: [6, 8], ci: 58,
    value: 64, unit: 'overtakes/h', threshold: 20, w: .19, conf: .61,
    src: 'Video analytics (overtake classification)',
    note: 'Early build-up window: overtaking into a metered downstream section creates stop-start waves.' },
  { cat: DRV, v: 'Proper use of loading/unloading', eff: 'decreases', place: ['path', 'ayala', .62],
    loc: 'Ayala Ave — 12 formal loading bays in service', hours: [10, 16], ci: 31,
    value: 88, unit: '% compliant loading', threshold: 70, w: .17, conf: .74,
    src: 'Post-intervention audit (loading-bay compliance)',
    note: 'Decreasing variable: the loading-bay programme is already delivering, which is why the inter-peak reads low.' },

  /* ---------------- Pedestrian — people in the carriageway -------------- */
  { cat: PED, v: 'Normal Citizens', eff: 'increases', place: ['bo', 'edsa-ayala'],
    loc: 'EDSA–Ayala at-grade crossings', hours: [7, 9], ci: 69,
    value: 1900, unit: 'peds/h', threshold: 900, w: .26, conf: .77,
    src: 'Pedestrian count survey (2 turning-movement counts)',
    note: 'At-grade crossings consume green time and put pedestrians in conflict with turning vehicles.' },
  { cat: PED, v: 'Normal Citizens', eff: 'increases', place: ['bo', 'sl-greenbelt'],
    loc: 'Dela Rosa × Greenbelt 3 crossings', hours: [17, 19], ci: 57,
    value: 1240, unit: 'peds/h', threshold: 800, w: .20, conf: .70,
    src: 'Mall access counts + pedestrian survey',
    note: 'Retail peaks overlap with the PM commuter peak, so the crossing is requested twice per cycle.' },
  { cat: PED, v: 'Street vendors (mga tusoktusok)', eff: 'increases', place: ['bo', 'poblacion-jpr'],
    loc: 'J.P. Rizal sidewalk market strip', hours: [11, 14], ci: 40,
    value: 46, unit: 'stalls along 300 m', threshold: 15, w: .14, conf: .58,
    src: 'Barangay vendor inventory 2026-09',
    note: 'Stalls and their customers narrow the walkable width, pushing pedestrians into the kerb lane.' },
  { cat: PED, v: 'Street vendors (mga tusoktusok)', eff: 'increases', place: ['path', 'ayala', .20],
    loc: 'Ayala Triangle Gardens approach', hours: [11, 13], ci: 33,
    value: 18, unit: 'stalls along 300 m', threshold: 10, w: .12, conf: .55,
    src: 'LGU vendor inventory + site walk',
    note: 'Lunchtime cluster; low pressure because the sidewalk here is 5 m wide.' },
  { cat: PED, v: 'Bikes', eff: 'decreases', place: ['path', 'poblacion', .60, 1],
    loc: 'Poblacion protected bike lane (J.P. Rizal to bridge)', hours: [6, 9], ci: 26,
    value: 240, unit: 'bikes/h', threshold: 100, w: .10, conf: .60,
    src: 'Bike counter (looped inductive detector)',
    note: 'Decreasing variable: the protected lane removes short CBD trips from mixed traffic.' },
  { cat: PED, v: 'Slow pedestrian?', eff: 'increases', place: ['bo', 'sl-legazpi'],
    loc: 'Legazpi Village school zone crossing', hours: [7, 8], ci: 42,
    value: 0.9, unit: 'm/s crossing speed', threshold: 1.2, w: .13, conf: .56,
    src: 'Crossing-speed spot survey (school escort groups)',
    note: 'Escorted children cross below the design speed, extending the pedestrian phase needed per group.' },
  { cat: PED, v: 'Mga namamarang public transpo', eff: 'increases', place: ['path', 'buendia', .62],
    loc: 'Buendia westbound kerb (informal flag-down)', hours: [17, 19], ci: 65,
    value: 96, unit: 'informal boardings/h', threshold: 30, w: .22, conf: .62,
    src: 'Kerb observation count + PUV stop overlay',
    note: 'Passengers hailing anywhere along the kerb make every 40 m a potential 20 s stop.' },
  { cat: PED, v: 'Number of passengers', eff: 'increases', place: ['bo', 'edsa-ayala'],
    loc: 'MRT-3 Ayala platform and bus bay', hours: [17, 20], ci: 84,
    value: 10600, unit: 'passengers/h', threshold: 6000, w: .31, conf: .80,
    src: 'MRT-3 tap counts + bus APC (automatic passenger counter)',
    note: 'Platform demand is the root driver of the transfer queue that spills onto EDSA.' },

  /* ---------------- Safety hazards -------------------------------------- */
  { cat: SAF, v: 'Crashes/Collisions', eff: 'increases', place: ['bo', 'edsa-buendia'],
    loc: 'EDSA × Buendia main carriageway', hours: [17, 19], ci: 83,
    value: 3, unit: 'crashes in window', threshold: 0, w: .27, conf: .74,
    src: 'MMDA incident feed + PNP blotter',
    note: 'Active crashes inside the analysis window; each one removes a lane for ~22 minutes.' },
  { cat: SAF, v: 'Potholes (Sira sa mismong kalsada)', eff: 'increases', place: ['path', 'buendia', .72],
    loc: 'Buendia eastbound (Chino Roces to EDSA)', hours: [0, 23], ci: 44,
    value: 14, unit: 'defects/km', threshold: 4, w: .16, conf: .60,
    src: 'Pavement condition survey 2026-08',
    note: 'Full-day variable: drivers slow to 20 km/h over the worst 180 m regardless of demand.' },
  { cat: SAF, v: 'Broke down vehicles', eff: 'increases', place: ['path', 'edsa', .70],
    loc: 'EDSA northbound inner lane', hours: [6, 9], ci: 60,
    value: 5, unit: 'breakdowns/30 days', threshold: 1, w: .19, conf: .63,
    src: 'Towing contractor dispatch logs',
    note: 'Breakdowns cluster in the AM peak and are cleared in 18 minutes on average.' },
  { cat: SAF, v: 'EMERGENCY VEHICLES (Police or ambulance and such)', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [0, 23], ci: 30,
    value: 4, unit: 'priority responses/day', threshold: 0, w: .10, conf: .50,
    src: 'Dispatch log (Makati DRRMO + PNP)',
    note: 'Intermittent but high-impact: a siren run stops cross-traffic for 40–90 s with no pattern.' },

  /* ---------------- Events and calendar --------------------------------- */
  { cat: EVT, v: 'Peak-hour/rush hour', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [17, 19], ci: 90,
    value: 1.9, unit: 'demand / design', threshold: .85, w: .40, conf: .92,
    src: '24-hour probe profile + volume counts',
    note: 'Context variable: the PM peak is the binding constraint for every corridor in this build.' },
  { cat: EVT, v: 'Peak-hour/rush hour', eff: 'increases', place: ['path', 'edsa', .40],
    loc: 'EDSA transit belt', hours: [7, 9], ci: 89,
    value: 1.85, unit: 'demand / design', threshold: .85, w: .38, conf: .90,
    src: '24-hour probe profile + volume counts',
    note: 'AM peak on the belt is directional: inbound demand saturates the three mixed lanes by 07:20.' },
  { cat: EVT, v: 'Workday vs regular day', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [6, 20], ci: 73,
    value: 88, unit: '% of weekday office load', threshold: 60, w: .26, conf: .80,
    src: 'Office occupancy survey + employer travel plans',
    note: 'Hybrid work keeps the peak narrower but sharper: fewer trips, more of them in one hour.' },
  { cat: EVT, v: 'Morning vs afternoon/time of day traffic', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [6, 12], ci: 62,
    value: 0.86, unit: 'AM:PM volume ratio', threshold: 1, w: .17, conf: .72,
    src: 'Directional volume counts 2026-08',
    note: 'AM is 14% smaller than PM but more directional, so one carriageway fails first.' },
  { cat: EVT, v: 'School day vs regular day', eff: 'increases', place: ['bo', 'sl-legazpi'],
    loc: 'Legazpi Village school cluster', hours: [6, 8], ci: 58,
    value: 6, unit: 'schools inside 25 min', threshold: 2, w: .20, conf: .70,
    src: 'School calendar + bell-schedule inventory',
    note: 'Calendar variable: adding school days to a normal weekday moves 160 drop-offs into 25 minutes.' },
  { cat: EVT, v: 'Parades', eff: 'increases', place: ['path', 'ayala', .50],
    loc: 'Ayala Ave civic parade route', hours: [15, 17], ci: 78,
    value: 2, unit: 'events/month', threshold: 0, w: .24, conf: .70,
    src: 'City events permit calendar',
    note: 'Permitted closures remove the whole carriageway, so the diversion load hits Buendia and EDSA.' },
  { cat: EVT, v: 'VIPs?', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network (motorcade corridors)', hours: [0, 23], ci: 46,
    value: 3, unit: 'escorts/month', threshold: 0, w: .12, conf: .55,
    src: 'LGU security liaison (anonymised)',
    note: 'Unpredictable rolling closures; kept in the template because they dominate incident logs when they occur.' },
  { cat: EVT, v: 'Holiday vs regular day', eff: 'decreases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [0, 23], ci: 32,
    value: -38, unit: '% demand vs weekday', threshold: 0, w: .14, conf: .68,
    src: 'Holiday volume comparison (2026 calendar)',
    note: 'Decreasing variable: regular holidays cut CBD demand by roughly a third.' },
  { cat: EVT, v: 'Fiesta', eff: 'increases', place: ['path', 'poblacion', .40, 0],
    loc: 'Poblacion fiesta streets', hours: [0, 23], ci: 51,
    value: 2, unit: 'fiestas/year', threshold: 0, w: .15, conf: .58,
    src: 'Barangay fiesta calendar (Sto. Niño, Poblacion)',
    note: 'Processions and street stalls close minor streets for a day, pushing traffic onto J.P. Rizal.' },
  { cat: EVT, v: 'Pag may patay', eff: 'increases', place: ['bo', 'poblacion-jpr'],
    loc: 'Barangay funeral procession routes', hours: [0, 23], ci: 38,
    value: 2, unit: 'processions/month', threshold: 0, w: .11, conf: .50,
    src: 'Barangay hall logs (anonymised)',
    note: 'Slow-moving processions block narrow Poblacion streets for 20–40 minutes at short notice.' },

  /* ---------------- Weather --------------------------------------------- */
  { cat: WX, v: 'Rainfall/harsh winds', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [12, 20], ci: 61,
    value: 22, unit: 'mm/h peak intensity', threshold: 7.5, w: .24, conf: .79,
    src: 'PAGASA gauge (nearest station) + LGU flood reports',
    note: 'Rain cuts carousel and jeepney speeds first, then the CBD links through queue spillback.' },
  { cat: WX, v: 'Floods', eff: 'increases', place: ['path', 'buendia', .22],
    loc: 'Buendia low-lying section (west of Chino Roces)', hours: [15, 19], ci: 79,
    value: 0.4, unit: 'm standing water', threshold: 0.05, w: .28, conf: .71,
    src: 'LGU flood monitoring + DPWH drainage records',
    note: 'Standing water removes the kerb lane, so a heavy-rain event turns Buendia into a one-lane corridor.' },
  { cat: WX, v: 'Temperature/Harsh Sun', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [11, 15], ci: 53,
    value: 34, unit: '°C feels-like', threshold: 33, w: .18, conf: .74,
    src: 'PAGASA temperature + heat-index calculation',
    note: 'Extreme heat slows crossings and keeps vehicles idling with air-conditioning load.' },
  { cat: WX, v: 'Fogs/Road visibility', eff: 'increases', place: ['bo', 'sl-legazpi'],
    loc: 'Legazpi Village (pre-dawn)', hours: [4, 6], ci: 37,
    value: 600, unit: 'm visibility', threshold: 1000, w: .12, conf: .60,
    src: 'PAGASA visibility observation',
    note: 'Rare in Makati, but the template keeps the row so the weather category is never silently dropped.' },
  { cat: WX, v: 'Possibility of hail/icy roads', eff: 'increases', place: ['pt', 14.5547, 121.0244],
    loc: 'Makati CBD network', hours: [0, 23], ci: 12,
    value: 0, unit: 'events/year in record', threshold: 0, w: .05, conf: .45,
    src: 'Climatological record review',
    note: 'Low-probability context row: present so the schema can carry zero-incidence variables without gaps.' }
];
